#!/usr/bin/env python
# -----------------------------------------------------
# AUTO-GENERATE BATCH SCRIPT TO RUN THE EP WORKFLOW,
# AND LAUNCH IT VIA sbatch
# -----------------------------------------------------
# EXAMPLE:
# EP_batch -N 1 -n 1 -t 1 -e alpopa@ipp.mpg.de -q gen9_ib-short -c user_profiles/default/

import argparse
import subprocess
from datetime import datetime


def write_batch_script(
    batch_file_name, nproc, job_time, queue, config_folder, email=None, memory=None, additional_kwargs=None, verbose=True
):
    with open(batch_file_name, "w") as batch_file:
        batch_file.write(f"#!/bin/sh\n")
        batch_file.write(f"#SBATCH  --nodes=1\n")
        batch_file.write(f"#SBATCH  --ntasks-per-node={nproc}\n")
        batch_file.write(f"#SBATCH  --cpus-per-task=1\n")
        job_hours = int(job_time)
        job_minutes = int(round((job_time - int(job_time)) * 60))
        batch_file.write(f"#SBATCH  --time={job_hours:02d}:{job_minutes:02d}:00\n")
        if email is not None:
            batch_file.write(f"#SBATCH  --mail-user={email}\n")
            batch_file.write(f"#SBATCH  --mail-type=END\n")
        else:
            batch_file.write(f"#SBATCH  --mail-type=NONE\n")
        if memory is not None:
            batch_file.write(f"#SBATCH  --mem={memory}\n")
        batch_file.write(f"#SBATCH  --job-name=EP_wf\n")
        if queue is not None:
            batch_file.write(f"#SBATCH  --partition={queue}\n\n")
        if additional_kwargs is not None:
            for k,v in additional_kwargs.items():
                if v is not None:
                    batch_file.write(f"#SBATCH  --{k}={v}\n")
        batch_file.write(f"ep_nogui -c {config_folder}\n")


def submit_batch_script(batch_file_name, verbose=True):
    subprocess.call(["sbatch " + batch_file_name], shell=True)
    if verbose:
        print(f"{batch_file_name} submitted.")


if __name__ == "__main__":
    # Management of input arguments
    parser = argparse.ArgumentParser(
        description="---- Run the EP workflow without the interface"
    )
    parser.add_argument(
        "-n", "--nproc", type=int, default=1, help="Number of processors/node"
    )
    parser.add_argument(
        "-t", "--time", type=int, default=2, help="Required cpu time in hours"
    )
    parser.add_argument(
        "-e", "--email", type=str, help="E-mail where to send job resulting status"
    )
    parser.add_argument("-q", "--queue", type=str, help="Name of the batch queue")
    parser.add_argument(
        "-c", "--config_folder", required=True, help="input configuration folder"
    )
    args = parser.parse_args()

    auto_batch_name = str("auto_batch_" + datetime.now().strftime("%y%m%d_%H%M%S"))
    write_batch_script(
        auto_batch_name,
        args.nproc,
        args.time,
        args.queue,
        args.config_folder,
        email=args.email,
        memory=args.mem,
        additional_kwargs={"qos": args.qos}
    )
    if args.submit:
        submit_batch_script(auto_batch_name)
    else:
        print(f"{auto_batch_name} prepared; not submitted")
