#!/usr/bin/env python

# -----------------------------------------------------
# AUTO-GENERATE BATCH SCRIPT TO RUN THE EP WORKFLOW,
# AND LAUNCH IT VIA QSUB
# -----------------------------------------------------
# EXAMPLE:
# EP_batch -n 1 -t 1 -e alpopa@ipp.mpg.de -q gen9_ib-short

import argparse, subprocess

from datetime import datetime

# Management of input arguments
parser = argparse.ArgumentParser(description='---- Run the EP workflow without the interface')
parser.add_argument("-n","--nproc",help="Number of processors", required=True)
parser.add_argument("-t","--time",help="Required cpu time in hours", required=True)
parser.add_argument("-e","--email",help="E-mail where to send job resulting status", required=True)
parser.add_argument("-q","--queue",help="Name of the batch queue", required=True)

args          = vars(parser.parse_args())
nproc         = args["nproc"]
time          = args["time"]
email         = args["email"]
queue         = args["queue"]

auto_batch_name = str('auto_batch_'+datetime.now().strftime('%y%m%d_%H%M%S'))

with open(auto_batch_name, 'w') as file:

   file.write('#!/bin/sh\n\n')
   file.write('#SBATCH  --ntasks-per-node='+nproc+'\n')
   file.write('#SBATCH  --cpus-per-task=1'+'\n')
   file.write('#SBATCH  --time='+time+':00:00'+'\n')
   file.write('#SBATCH  --mail-user='+email+'\n')
   file.write('#SBATCH  --mail-type=END'+'\n')
   file.write('#SBATCH  --job-name=EP_wf'+'\n')
   file.write('#SBATCH  --partition='+queue+'\n\n')
   file.write('chmod +x ep_nogui \n')
   file.write('python ep_nogui.py \n')

file.close()

subprocess.call(['qsub '+auto_batch_name],shell=True)
print(auto_batch_name+' submitted.')