#!/usr/bin/env python

from ep_stability_wf.workflow.run_workflow import workflow_EP
import argparse
import os


# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Run the EP workflow without the interface"
)
parser.add_argument(
    "-c", "--config_folder", help="input configuration folder", required=True
)

args = vars(parser.parse_args())
config_folder = args["config_folder"]

workflow_EP(config_folder)
